{ lib, ... }:

{
  tmux.modules = [ ({ config, lib, pkgs, tmuxLib, ... }:
    let
      inherit (lib)
        concatMapStringsSep
        listToAttrs
        mapAttrs
        mapAttrsToList
        mkMerge
        mkOption
        mkOrder
        types;

      dag = tmuxLib.dag;

      plugins = lib.recursiveUpdate config.tmux.plugins config.tmux.extraPlugins;

      resolved =
        mapAttrs
          (name: p:
            let
              entry =
                dag.entryAfter p.after ''
                  ${concatMapStringsSep "\n"
                    (path: "run-shell '${p.package}/${path}'")
                    (
                      lib.optional (p.source != null) p.source
                      ++ p.sources
                    )
                  }
                  ${p.init}
                '';
            in { inherit name entry; })
          plugins;

      entries =
        listToAttrs (
          mapAttrsToList
            (_: p: { name = p.name; value = p.entry; })
            resolved
        );

    in {
      options.tmux.rc =
        mkOption {
          type = types.lines;
          internal = true;
          description = "Rendered tmux.conf content.";
        };

      config.tmux.rc =
        mkMerge [
          (mkOrder 0 ''
            # Generated by tmux — do not edit.
          '')

          (mkOrder 10 ''
            # Base options
            set -g mouse on
            set -g mode-keys vi
            set -g base-index 1
            setw -g pane-base-index 1
            set -g renumber-windows on

            # Window and pane splitting
            bind | split-window -h
            bind - split-window -v
            unbind '"'
            unbind %
          '')

          (mkOrder 50 ''
            # Plugins
            ${dag.render { inherit entries; }}
          '')
        ];
    }) ];
}
